steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/cloudrun-gmaps-scraper','$BUILD_DIR']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/cloudrun-gmaps-scraper']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run','deploy','cloudrun-gmaps-scraper','--image','gcr.io/$PROJECT_ID/cloudrun-gmaps-scraper','--region','us-central1','--platform','managed','--allow-unauthenticated']
timeout: '1200s'
